(global-set-key (kbd "C-c s")   'shell)
(global-set-key (kbd "C-x M-f") 'ido-find-file-other-window)
(global-set-key (kbd "C-c c")   'switch-to-previous-buffer)
(global-set-key (kbd "M-t")     'textmate-goto-file)
(global-set-key (kbd "M-T")     'textmate-goto-symbol)
(global-set-key (kbd "C-c d")   'duplicate-line)
(global-set-key (kbd "M-]")     'textmate-shift-right)
(global-set-key (kbd "M-[")     'textmate-shift-left)
(global-set-key (kbd "M-/")     'comment-region)
(global-set-key (kbd "C-x à")   'delete-window)
(global-set-key (kbd "C-x &")   'delete-other-windows)
(global-set-key (kbd "C-x é")   'split-window-below)
(global-set-key (kbd "C-x \"")  'split-window-right)
(global-set-key (kbd "M-l")     'goto-line)
(global-set-key (kbd "M-L")     'textmate-select-line)
(global-set-key (kbd "C-c ,s")  'rspec-verify-single)
(global-set-key (kbd "C-c o")   'vi-open-line-above)
(global-set-key (kbd "C-o")     'vi-open-line-below)
(global-set-key (kbd "C-c g")   'magit-status)
