(global-set-key "\C-cs" 'shell)
(global-set-key (kbd "C-x M-f") 'ido-find-file-other-window)
(global-set-key "\C-cc" 'switch-to-previous-buffer)
(global-set-key "\M-t" 'textmate-goto-file)
(global-set-key "\M-T" 'textmate-goto-symbol)
(global-set-key "\C-cd" 'duplicate-line)
(global-set-key "\M-]" 'textmate-shift-right)
(global-set-key "\M-[" 'textmate-shift-left)
(global-set-key "\M-/" 'comment-region)
(global-set-key "\C-xà" 'delete-window)
(global-set-key "\C-x&" 'delete-other-windows)
(global-set-key "\C-xé" 'split-window-below)
(global-set-key "\C-x\"" 'split-window-right)
(global-set-key "\M-l" 'goto-line)
(global-set-key "\M-L" 'textmate-select-line)
(global-set-key "\C-c,s" 'rspec-verify-single)
(global-set-key "\C-co" 'vi-open-line-above)
(global-set-key "\C-o" 'vi-open-line-below)
(global-set-key "\C-c g" 'magit-status)
