(global-set-key (kbd "M-x")          'helm-M-x)
(global-set-key (kbd "C-x b")        'helm-buffers-list)
(global-set-key (kbd "C-c s")        'shell)
(global-set-key (kbd "C-x C-v")      'ido-find-file-other-window)
(global-set-key (kbd "C-c c")        'switch-to-previous-buffer)
(global-set-key (kbd "M-t")          'helm-projectile-find-file)
(global-set-key (kbd "M-T")          'textmate-goto-symbol)
(global-set-key (kbd "C-c d")        'duplicate-line)
(global-set-key (kbd "M-]")          'textmate-shift-right)
(global-set-key (kbd "M-[")          'textmate-shift-left)
(global-set-key (kbd "M-/")          'comment-or-uncomment-region)
(global-set-key (kbd "C-x à")        'delete-window)
(global-set-key (kbd "C-x &")        'delete-other-windows)
(global-set-key (kbd "C-x é")        'split-window-below)
(global-set-key (kbd "C-x \"")       'split-window-right)
(global-set-key (kbd "M-L")          'textmate-select-line)
(global-set-key (kbd "C-c g")        'magit-status)
(global-set-key (kbd "M-l")          'goto-line-with-feedback)
(global-set-key (kbd "M-z")          'zap-up-to-char)
(global-set-key (kbd "C-x -")        'toggle-windows-split)
(global-set-key (kbd "<f12>")        'multi-term-dedicated-toggle)
(global-set-key (kbd "C-c p")        'partially/visit-partial)
(global-set-key (kbd "C-c ,,")       'ruby-open-spec-other-buffer)
(global-set-key (kbd "<C-S-down>")   'move-line-down)
(global-set-key (kbd "<C-S-up>")     'move-line-up)
(global-set-key (kbd "<C-return>")   'open-line-below)
(global-set-key (kbd "<C-S-return>") 'open-line-above)
(global-set-key (kbd "M-.")          'helm-etags-select)
(global-set-key (kbd "M-p")          'previous-multiframe-window)
(global-set-key (kbd "M-n")          'other-window)
(global-set-key (kbd "C-:")          'mark-all-like-this)

(define-key global-map (kbd "RET") 'newline-and-indent)
